Remove unused NormalizeBench::fUsePortable field.
To address build warnings:

../bench/MathBench.cpp:442:10: error: private field 'fUsePortable' is not used
[-Werror,-Wunused-private-field]
bool fUsePortable;
     ^

R=reed@google.com

Author: fmalita@chromium.org

Review URL: https://chromiumcodereview.appspot.com/17463002

git-svn-id: http://skia.googlecode.com/svn/trunk@9677 2bbb7eff-a529-9590-31e7-b0007b416f81